tag: 'LagrangianPPO'

setup:
  seed: 78348
  use_gpu: False

train:
  name: 'Cell-v0'
  verbose: 50

agent:
  n_step: 5000000
  steps_per_epoch: 3000
  clip: 0.2
  gamma: 0.99 
  gamma_c: 0.99
  penalty: 1.0

  pi_lr: 0.0003
  pi_iters: 80
  vf_lr: 0.001
  vf_iters: 80
  penalty_lr: 0.05

  logstd: -0.5

  actor:
    h_layers: 2
    h_size: 256
    print_model: True

  critic:
    h_layers: 2
    h_size: 256
    print_model: True


      

